version: '3.11'
services:
  app:
    image: chattube
    build: .
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ELEVEN_API_KEY: ${ELEVEN_API_KEY}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY}
      DEPLOYMENT_NAME: ${DEPLOYMENT_NAME}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
      AZURE_OPENAI_BASE: ${AZURE_OPENAI_BASE}
      AZURE_WHISPER_API_KEY: ${AZURE_WHISPER_API_KEY}
      AZURE_WHISPER_ENDPOINT: ${AZURE_WHISPER_ENDPOINT}
      AZURE_WHISPER_API_VERSION: ${AZURE_WHISPER_API_VERSION}
      AZURE_OPENAI_VERSION: ${AZURE_OPENAI_VERSION}
      AZURE_OPENAI_MODEL: ${AZURE_OPENAI_MODEL}
      TEMPERATURE: ${TEMPERATURE}
      CHAINLIT_MAX_SIZE_MB: ${CHAINLIT_MAX_SIZE_MB}
      CHAINLIT_MAX_FILES: ${CHAINLIT_MAX_FILES}
      TEXT_SPLITTER_CHUNK_SIZE: ${TEXT_SPLITTER_CHUNK_SIZE}
      TEXT_SPLITTER_CHUNK_OVERLAP: ${TEXT_SPLITTER_CHUNK_OVERLAP}
      EMBEDDINGS_CHUNK_SIZE: ${EMBEDDINGS_CHUNK_SIZE}
      MAX_RETRIES: ${MAX_RETRIES}
      RETRY_MIN_SECONDS: ${RETRY_MIN_SECONDS}
      RETRY_MAX_SECONDS: ${RETRY_MAX_SECONDS}
      TIMEOUT: ${TIMEOUT}
      DEBUG: ${DEBUG}
    volumes:
      - .:/usr/src/app
